routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\YazarController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::middleware(['auth', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', [MainController::class, 'dashboard'])->name('dashboard');
});

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix' => 'admin'], function () {
    Route::get('yazars/show/{id}', [YazarController::class, 'show'])->whereNumber('id')->name('yazars.show');
    Route::get('books/show/{id}', [BookController::class, 'show'])->whereNumber('id')->name('books.show');
    Route::get('yazars/{id}', [YazarController::class, 'destroy'])->whereNumber('id')->name('yazars.destroy');
    Route::get('books/{id}', [YazarController::class, 'destroy'])->whereNumber('id')->name('books.destroy');
    Route::resource('books', BookController::class);
    Route::resource('yazars', YazarController::class);
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $fillable = ['ad', 'barkod', 'sayfasayi', 'satisfiyat', 'yazar_id'];

    public function yazars() {
        return $this->belongsTo('App\Models\Yazar', Yazar::class);
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\Yazar;
use App\Http\Requests\BookCreateRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Yazar::join('books', 'books.yazar_id', '=', 'yazars.id')->select(['books.id', 'books.ad', 'books.yazar_id', 'books.barkod', 'books.sayfasayi', 'books.satisfiyat', 'yazars.isim'])->paginate(5);
        return view('admin.books.list', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $books = Yazar::get();
        return view('admin.books.create', compact('books'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookCreateRequest $request)
    {
        Book::create($request->post());
        return redirect()->route('books.index')->withSuccess('Kitap başarıyla oluşturuldu.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id) ?? abort(404, 'Kitap bulunamadı');
        return view('admin.books.edit', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id) ?? abort(404, 'Kitap bulunamadı');
        $yazar = DB::table('yazars')->get();
        return view('admin.books.edit', ['yazars' => $yazar], compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $book = Book::find($id) ?? abort(404, 'Kitap Bulunamadı');

        Book::where('id', $id)->update($request->except(['_method', '_token']));

        return redirect()->route('books.index')->withSuccess('Kitap Güncelleme başarıyla gerçekleşti.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Yazar::find($id) ?? abort(404, 'Kitap Bulunamadı');
        $book->delete();
        return redirect()->route('books.index')->withSuccess('Kitap silme işlemi başarıyla gerçekleşti.');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/books/create.blade.php
<x-app-layout>
    <x-slot name="header">
        Kitap Oluştur
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <form action="{{route('books.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label>Kitap Adı</label>
                    <input type="text" name="ad" class="form-control">
                </div>
                <div class="form-group">
                    <label>Yazar Adı</label>
                    <select class="form-control" name="yazar_id">
                        <option value="0">Yazar Seçiniz</option>
                        @foreach ($books as $book)  
                        <option value="{{$book->id}}">{{$book->isim}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Barkod No</label>
                    <input type="text" name="barkod" class="form-control">
                </div>
                <div class="form-group">
                    <label>Sayfa Sayısı</label>
                    <input type="text" name="sayfasayi" class="form-control">
                </div>
                <div class="form-group">
                    <label>Piyasa Satış Fiyatı</label>
                    <input type="text" name="satisfiyat" class="form-control">
                </div>
                <br>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm btn-block">Kitap Oluştur</button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/admin/books/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        Kitabı Güncelle
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{{route('books.update', $book->id)}}">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label>Kitap Adı</label>
                    <input type="text" name="ad" class="form-control" value="{{$book->ad}}">
                </div>
                <div class="form-group">
                    <label>Yazar Adı</label>
                    <select class="form-control" name="yazar_id">
                        <option value="0">Yazar Seçiniz</option>
                        @foreach ($yazars as $yazar)  
                        <option value="{{$yazar->id}}">{{$yazar->isim}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Barkod</label>
                    <input type="text" name="barkod" class="form-control" value="{{$book->barkod}}">
                </div>
                <div class="form-group">
                    <label>Sayfa Sayısı</label>
                    <input type="text" name="sayfasayi" class="form-control" value="{{$book->sayfasayi}}">
                </div>
                <div class="form-group">
                    <label>Satış Fiyatı</label>
                    <input type="text" name="satisfiyat" class="form-control" value="{{$book->satisfiyat}}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm btn-block">Kitabı Düzenle</button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/admin/books/list.blade.php
<x-app-layout>
    <x-slot name="header">
        Kitaplar
    </x-slot>
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ route('books.create') }}" class="btn btn-sm btn-primary">Kitap Oluştur</a>
        </h5>
        <table class="table table-bordered bg-white">
            <thead>
                <tr>
                    <th scope="col">Kitap</th>
                    <th scope="col">Yazar</th>
                    <th scope="col">Barkod No</th>
                    <th scope="col">Sayfa Sayısı</th>
                    <th scope="col">Piyasa Satış Fiyatı</th>
                    <th scope="col">İşlem</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($books as $book)                    
                <tr>
                    <td>{{$book->ad}}</td>
                    <td><a href="/admin/yazars/show/{!! $book->yazar_id !!}">{{$book->isim}}</a></td>
                    <td>{{$book->barkod}}</td>
                    <td>{{$book->sayfasayi}}</td>
                    <td>{{$book->satisfiyat}}</td>
                    <td>
                        <a href="{{route('books.edit', $book->id)}}" class="btn-sm btn-primary">Düzenle</a>
                        <a href="{{route('books.destroy', $book->id)}}" class="btn-sm btn-danger">Sil</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{$books->links()}}
    </div>
</x-app-layout>

resources/views/admin/books/show.blade.php
<x-app-layout>
    <x-slot name="header">
        Kitap Oluştur
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <form action="{{route('books.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label>Kitap Adı</label>
                    <input type="text" name="ad" class="form-control">
                </div>
                <div class="form-group">
                    <label>Barkod No</label>
                    <input type="text" name="barkod" class="form-control">
                </div>
                <div class="form-group">
                    <label>Sayfa Sayısı</label>
                    <input type="text" name="sayfasayi" class="form-control">
                </div>
                <div class="form-group">
                    <label>Piyasa Satış Fiyatı</label>
                    <input type="text" name="satisfiyat" class="form-control">
                </div>
                <br>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm btn-block">Kitap Oluştur</button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>