routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\Admin\YazarController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::middleware(['auth', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::group(['middleware' => 'auth'], function() {
    Route::get('/dashboard', [MainController::class, 'dashboard'])->name('dashboard');
});

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix' => 'admin'], function () {
    Route::get('yazars/show/{id}', [YazarController::class, 'show'])->whereNumber('id')->name('yazars.show');
    Route::get('books/show/{id}', [BookController::class, 'show'])->whereNumber('id')->name('books.show');
    Route::get('yazars/{id}', [YazarController::class, 'destroy'])->whereNumber('id')->name('yazars.destroy');
    Route::get('books/{id}', [YazarController::class, 'destroy'])->whereNumber('id')->name('books.destroy');
    Route::resource('books', BookController::class);
    Route::resource('yazars', YazarController::class);
});

app/Models/Yazar.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Yazar extends Model
{
    use HasFactory;

    protected $fillable = ['isim', 'yas', 'dogumtarih', 'olumtarih'];

    public function books() {
        return $this->hasMany('App\Models\Book');        
    }
}

app/Http/Controllers/Admin/YazarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Yazar;

class YazarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $yazars = Yazar::paginate(5);
        return view('admin.yazars.list', compact('yazars'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.yazars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Yazar::create($request->post());
        return redirect()->route('yazars.index')->withSuccess('Yeni yazar başarıyla eklendi.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $yazar = Yazar::find($id) ?? abort(404, 'Yazar bulunamadı');
        return view('admin.yazars.show', compact('yazar'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $yazar = Yazar::find($id) ?? abort(404, 'Yazar bulunamadı');
        return view('admin.yazars.edit', compact('yazar'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $yazar = Yazar::find($id) ?? abort(404, 'Yazar Bulunamadı');

        Yazar::where('id', $id)->update($request->except(['_method', '_token']));

        return redirect()->route('yazars.index')->withSuccess('Yazar Güncelleme başarıyla gerçekleşti.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $yazar = Yazar::find($id) ?? abort(404, 'Yazar Bulunamadı');
        $yazar->delete();
        return redirect()->route('yazars.index')->withSuccess('Yazar silme işlemi başarıyla gerçekleşti.');

    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/yazars/create.blade.php
<x-app-layout>
    <x-slot name="header">
        Yazar Oluştur
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <form action="{{route('yazars.store')}}" method="post">
                @csrf
                <div class="form-group">
                    <label>Yazar Adı Soyadı</label>
                    <input type="text" name="isim" class="form-control">
                </div>
                <div class="form-group">
                    <label>Yaş</label>
                    <input type="text" name="yas" class="form-control">
                </div>
                <div class="form-group">
                    <label>Doğum Tarihi</label>
                    <input type="datetime-local" name="dogumtarih" class="form-control">
                </div>
                <div class="form-group">
                    <label>Ölüm Tarihi</label>
                    <input type="datetime-local" name="olumtarih" class="form-control">
                </div>
                <br>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm btn-block">Kitap Oluştur</button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/admin/yazars/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        Yazarı Güncelle
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{{route('yazars.update', $yazar->id)}}">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label>Yazar Adı</label>
                    <input type="text" name="isim" class="form-control" value="{{$yazar->isim}}">
                </div>
                <div class="form-group">
                    <label>Yaş</label>
                    <input type="text" name="yas" class="form-control" value="{{$yazar->yas}}">
                </div>
                <div class="form-group">
                    <label for="">Doğum Tarihi</label>
                    <input type="datetime-local" name="dogumtarih" class="form-control" value="{{ date('Y-m-d\TH:i', strtotime($yazar->dogumtarih)) }}">
                    <br>
                </div>
                <div class="form-group">
                    <label for="">Ölüm Tarihi</label>
                    <input type="datetime-local" name="olumtarih" class="form-control" value="{{ date('Y-m-d\TH:i', strtotime($yazar->olumtarih)) }}">
                    <br>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-sm btn-block">Yazarı Düzenle</button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/admin/yazars/list.blade.php
<x-app-layout>
    <x-slot name="header">
        Yazarlar
    </x-slot>
    <div class="card-body">        
        <h5 class="card-title">
            <a href="{{ route('yazars.create') }}" class="btn btn-sm btn-primary">Yazar Oluştur</a>
        </h5>
        <h5 class="card-title">
        </h5>
        <table class="table table-bordered bg-white">
            <thead>
                <tr>
                    <th scope="col">Yazar</th>
                    <th scope="col">Yaş</th>
                    <th scope="col">Doğum Tarihi</th>
                    <th scope="col">Ölüm Tarihi</th>
                    <th scope="col">İşlem</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($yazars as $yazar)             
                <tr>
                    <td><a href="/admin/yazars/show/{!! $yazar->id !!}">{{$yazar->isim}}</a></td>
                    <td>{{$yazar->yas}}</td>
                    <td>{{$yazar->dogumtarih}}</td>
                    <td>{{$yazar->olumtarih}}</td>
                    <td>
                        <a href="{{route('yazars.edit', $yazar->id)}}" class="btn-sm btn-primary">Düzenle</a>
                        <a href="{{route('yazars.destroy', $yazar->id)}}" class="btn-sm btn-danger">Sil</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{$yazars->links()}}
    </div>
</x-app-layout>

resources/views/admin/yazars/show.blade.php
<x-app-layout>
    <x-slot name="header">
        {{$yazar->isim}}
    </x-slot>
    <p></p>
    <div class="card">
        <div class="card-body">
            <a href="javascript:history.back(-1);" class="btn-sm btn-success">Geri Dön</a>
            <a href="{{route('yazars.edit', $yazar->id)}}" class="btn-sm btn-primary">Düzenle</a>
            <a href="{{route('yazars.destroy', $yazar->id)}}" class="btn-sm btn-danger">Sil</a>
            <br><br>
                <div class="form-group">
                    <label>Yaş</label>
                    <input type="text" name="yas" class="form-control" disabled="disabled" value="{{$yazar->yas}}">
                    <br>
                </div>
                <div class="form-group">
                    <label for="">Doğum Tarihi</label>
                    <input type="datetime-local" name="dogumtarih" class="form-control" disabled="disabled" value="{{ date('Y-m-d\TH:i', strtotime($yazar->dogumtarih)) }}">
                    <br>
                </div>
                <div class="form-group">
                    <label for="">Ölüm Tarihi</label>
                    <input type="datetime-local" name="olumtarih" class="form-control" disabled="disabled" value="{{ date('Y-m-d\TH:i', strtotime($yazar->olumtarih)) }}">
                    <br>
                </div>
        </div>
    </div>
</x-app-layout>